### ISSUE TITLE
Update CMEPS restart test case with new oro data with lake frac/depth

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-s2s-model#108]
In current s2s CMEPS restart regression test, the reproducibility is achieved when oro data does not contain the lake frac and lake depth record, therefore lake points won't be differentiated from ocean points in the oceanfrac in fv3, so lake temperature will have the issue of taking ocean points temperature. In this ticket, the oro data is updated with lake fract and lake depth, the restart reproducibility issue will be fixed.

**Comment by DeniseWorthen** [comment]
I have tested the restart repro at c384 using our sandbox on cheyenne. I obtained from Shan the updated c384 input data for 20120101 (oro, sfc_data and gfs_data). I updated FV3 (def9be1) so it can accept a single input_nml variable frac_grid true or false. The oro_data does contain both lake_frac and lake_depth. 

Running with frac_grid=F, I obtain the same 7 fields in FV3 differing on restart as noted here: [https://github.com/ufs-community/ufs-s2s-model/issues/34#issuecomment-636849261](https://github.com/ufs-community/ufs-s2s-model/issues/34#issuecomment-636849261)

**Comment by junwang-noaa** [comment]
The issue still exists in Moorthi's SM_Jul232020 branch.

**Comment by DeniseWorthen** [comment]
I would like to close this issue and also issue #34. I believe both are covered by new ufs-weather issue [227](https://github.com/ufs-community/ufs-weather-model/issues/227).

**Comment by DeniseWorthen** [comment]
Restart issues for the coupled model will be continued in ufs-weather issue [227](https://github.com/ufs-community/ufs-weather-model/issues/227)
