### ISSUE TITLE
contrib module change on Hera

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [ufs-community/ufs-s2s-model#109]
Hera modules need to be updated due to changes in contrib software packages (as of 20200611):
module load modules.nems fails due to not being able to load sutils and cmake/3.9.0

FROM
module load contrib sutils
TO
module use -a /contrib/sutils/modulefiles
module load sutils

FROM
module use /contrib/modulefiles
module load cmake/3.9.0
TO
module use /contrib/cmake/modulefiles
module load cmake/3.9.0

**Comment by junwang-noaa** [comment]
Thanks for looking into it, Minsuk. We made changes in ufs-weather, not yet
adding the change in s2s. Would you please make a PR for this one? Thanks

**Comment by MinsukJi-NOAA** [comment]
OK. It looks like the weather-model went from cmake 3.9.0 (in /contrib/cmake/modulefiles) to cmake 3.16.1 (in /apps/modules/modulefiles). I suppose this change should be fine as well for s2s-model?

**Comment by climbfuji** [comment]
Yes - 3.15 is now the minimum requirement.

**Comment by MinsukJi-NOAA** [comment]
Thanks, Dom.

**Comment by MinsukJi-NOAA** [comment]
Closing this issue as the related code changes were merged in (#110).
