### ISSUE TITLE
check for negative frozen precip

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-s2s-model#114]
In earlier runs (p3.1?) gross-checks determined that there was negative precipitation ( -7.980455e-15 ) in the ocean/ice models.   There was no negative frozen precipitation exported from atm model, so this appears to come from the mediator.  After migrating to CMEPS, we should check to see if this is still an issue and if so, make sure to add a check that frozen precipitation (or other values that should not be positive) are checked for and bounded.  (Similar to what was done for ice fraction in the atm model).

**Comment by DeniseWorthen** [comment]
In believe I determined that this occurs in the NEMS mediator when ice weight ~ 1.+eps where eps is a very small number. The atmwgt used to merge the frozen precip to the ocean is weighted by 1-icewgt; this can produce a -eps*frozen_precip going to the ocean.

**Comment by JessicaMeixner-NOAA** [comment]
Should we leave this to do one more check later or close this issue then?

**Comment by DeniseWorthen** [comment]
We did see this previously in some cmeps runs also (e-27 frozen precip). However, I believe the fix we have coming for the isolated coastal anomalies in cmeps (issue #116) might resolve the issue in cmeps. So we should check when we do the v0.6.1 comparisons and go from there maybe.

**Comment by junwang-noaa** [comment]
It looks to me CMEPS is doing the same as NEMS. Hope the upcoming CMEPS fix
will resolve the issue.

**Comment by DeniseWorthen** [comment]
@LydiaStefanova-NOAA checked a single 35-d cmeps run I made using the upcoming commit for the coastal anomalies (issue #116) and reported that the negative fprec which had appeared in the earlier validation run was gone.

**Comment by DeniseWorthen** [comment]
@LydiaStefanova-NOAA has confirmed that no negative frozen precip was present in the 8 35d runs prepared for the CICE6 validation. 

I am closing this issue.
