### ISSUE TITLE
remove resolution identifier from ice input files

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-s2s-model#12]
The ice_in_template names for grid_file and kmt_file should be changed to generic names which do not reference the grid resolution. This would allow both 1/2 and 1/4 deg models to run with same ice_in_template.

**Comment by JessicaMeixner-NOAA** [comment]
Or we could make the names of the file something that we put in as a variable in the template?

**Comment by DeniseWorthen** [comment]
For the restarts, we copy the file with the date and resolution into a generic name that the ice_in expects into the run directory. It is simple to repeat that with the grid and kmt files. The original files can still have the resolution identifiers, but the copy in the run directory will be a generic name.

**Comment by mvertens** [comment]
@Denise Worthen - NOAA Affiliate <denise.worthen@noaa.gov> @Jessica Meixner
- NOAA Affiliate <jessica.meixner@noaa.gov> Our experience in CESM is that
it is not a good idea to copy to a generic name. We used to do that a long
time ago and it led to a lot of errors that were not easy to detect. I am
happy to go over our current process if you both are interested.

**Comment by DeniseWorthen** [comment]
Closing issue for now; conversion of regression testing to rt.sh will most address this issue.
