### ISSUE TITLE
convert four_to_grid_stochy.F to four_to_grid_stochy.f error on Orion

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-s2s-model#131]
when compiling, there is one step which uses c++ compiler to convert "four_to_grid_stochy.F" to "four_to_grid_stochy.f", sometimes it failed and give a zero size "four_to_grid_stochy.f".
This only happens on Orion, works fine on HERA.

**Comment by MinsukJi-NOAA** [comment]
i have had the same problem sometime ago.

**Comment by jiandewang** [comment]
this issue can be closed when Bin's new PR is done which contains the fixing for it.
