### ISSUE TITLE
removal of NEMSCompsetRun files

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-s2s-model#134]
Files associated with the NEMSCompsetRun are no longer being used or maintained. They should be removed from ufs-s2s-model. This includes the appBuilder files and the compsets subdirectory.

**Comment by MinsukJi-NOAA** [comment]
NEMSCompsetRun files may still be used by NightlyTest @RatkoVasic-NOAA

**Comment by RatkoVasic-NOAA** [comment]
@MinsukJi-NOAA , I suggest abandoning old tests. I haven't checked results since we work from home (my bookmarks were on my work PC).  And I'm pretty sure nobody else looked at it.
