### ISSUE TITLE
Test FMS tag 2019.01.03-rc in S2S

### ISSUE THREAD

**Issue by binli2337** [ufs-community/ufs-s2s-model#136]
The following tests will be made:

1. Test FMS 2019.01.03-rc in current s2s (July 14, 2020 version, 0a0dc4b)
2. Test FMS 2019.01.03-rc in s2s with the most recent MOM6-interface (July 14, 2020 version, 2b22afd)
3. Test FMS 2019.01.03-rc in s2s with the the most recent fv3atm (July 14, 2020 version, da1230d) and MOM6-interface (July 14,2020 version, 2b22afd)

**Comment by junwang-noaa** [comment]
Bin, Please do not test FMS in the current s2s, FV3 needs to be updated to
20200701 version or later.

**Comment by binli2337** [comment]
The test using FMS 2019.01.03 with updated fv3atm (July 14, 2020 version, da1230d) and MOM6-interface (July 14,2020 version, 2b22afd) is successful.
