### ISSUE TITLE
make wave component optional in s2s 35 day test

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-s2s-model#142]
Currently s2s has a 35 day test set up with 4 coupled components: fv3, mom6, cice5 and ww3.  

ufs-s2s-model/tests/rt_35d_cmeps.conf

To run the 8 cases 35 day run:
cd ufs-s2s-model/tests
./rt.sh -l rt_35d_cmeps.conf
 
In this issue, we would like to add the capability of making wave component optional when running the 35 day test.

**Comment by DeniseWorthen** [comment]
We made an issue almost at the same time. I can close mine. I had asked @BrianCurtis-NOAA if he would like to take stab at it.

**Comment by DeniseWorthen** [comment]
I had also asked Minsuk if we could possibly add another column to rt.conf which would contain the date to run the test for. We could have only 2 test files (one for cold, one for 35d) which would use the date in rt.conf instead of 16 (8 cold and 8 35 day) test files.

**Comment by DeniseWorthen** [comment]
The second half of this issue (making the 35d tests run using the date in an extra column) has been merged. The non-wave 35d tests can now be made using a new non-wave rt 35d conf file and only two additional tests which replicate the new cpld_fv3_ccpp_384_mom6_cice_ww3_cmeps_cold and cpld_fv3_ccpp_384_mom6_cice_ww3_cmeps_35d.

**Comment by BrianCurtis-NOAA** [comment]
PR #153
