### ISSUE TITLE
current cold1 run sequence produces zero for ocean imports on first coupling timestep

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-s2s-model#167]
**Describe the bug**
The currrent cold1 run sequence ("coldstart") produces 0.0 for ocean import fields on first coupling timestep when restarting from coldstart

**To Reproduce**
All current implementations of ufs-s2s-model in regression tests and prototype workflows using the existing coldstart run sequence are impacted.

Use dbug >1 in mom_cap to turn on state_diagnose function in MOM6 and run any reststart-from-coldstart regression test. Examine the PET logs from Ocn at first ModelAdvance.

**Expected behavior**
Ocean imports at first coupling timestep should not be zero

**Additional context**
See attached presentation for further documentation of issue and proposed fixes. 

[remove_2step_coldstart.pdf](https://github.com/ufs-community/ufs-s2s-model/files/5112317/remove_2step_coldstart.pdf)

Also documented here: [#86](https://github.com/ufs-community/ufs-s2s-model/issues/86)

**Comment by DeniseWorthen** [comment]
@junwang-noaa Should I put the fix for the existing 2-step cold start (rearrange the cmeps cold run sequence) in the s2s-cice6 commit? Otherwise, an entire new baseline will need to be created if we first want to fix the 2-step before making it optional.

**Comment by junwang-noaa** [comment]
That would be good.

**Comment by junwang-noaa** [comment]
Is the s2s-cice6 commit ready to commit after this change?

**Comment by DeniseWorthen** [comment]
I was ready to start creating baselines. I am just waiting for the go-ahead that I should start. I think Jessica is part-way through her baseline creation. 

I also need the NEMS commit for the CICE6 commit. Since Jessica is relying on the reference to the current MOM6 directories in component_MOM6.mk for her commit, it is probably best to go w3, then cice6.

**Comment by junwang-noaa** [comment]
Yes, that is what we discussed at yesterday's meeting. I haven't seen any
update in #171, I am checking with Jessica.
