### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by benjamin-cash** [ufs-community/ufs-s2s-model#170]
**Describe the bug**
When output_grid is  set to 'global_latlon' or 'gaussian_grid', coastlines are outlined by missing values. This behavior does not appear when output_grid is set to 'cubed_sphere_grid'.

**To Reproduce**
Issue appeared when running https://github.com/DeniseWorthen/ufs-s2s-model branch feature/rtres on both Cheyenne and Stampede2 at C192_mx050

Error is visible in all fields

**Expected behavior**
No missing values.

**Additional context**
Run directory including output files showing the problem are here:  /glade/scratch/bcash/ufs-s2s-model/compile_test/ufs-s2s-model/rundir

EDIT: I was wrong about the ocean resolution, it is the half degree ocean.

**Comment by DeniseWorthen** [comment]
This is c192-mx050 test case which I have been running on Cheyenne to debug the wave-cice6 issue also.

**Comment by benjamin-cash** [comment]
Here is an example of what it looks like.
<img width="773" alt="Screen Shot 2020-08-26 at 4 37 06 PM" src="https://user-images.githubusercontent.com/62720073/91354304-8a648c00-e7ba-11ea-97bf-16c8f0e92c44.png">

**Comment by uturuncoglu** [comment]
The range seems normal to me. What is the actual value on those regions? Those could be the coastline generated by the ncview? Just an idea.

**Comment by bingfu-NOAA** [comment]
I assume this is a bug of ncview software. I found previously FV3 first and second tile orog fix files have same display issue.  It is more clear if you look at a lower resolution file, like  C96_oro_data.tile2.nc. 
But it looks like the data are fine. I also checked with a different display utility, it looks fine.
I attached the link file when I investigated this issue. 
https://docs.google.com/presentation/d/1TAJQmihUtE1oqGrbiglPh3g-pcefLGCVKOH9tENnU40/edit?usp=sharing

**Comment by benjamin-cash** [comment]
For comparison, here is a shot from the tiled output.
<img width="592" alt="Screen Shot 2020-08-26 at 4 49 08 PM" src="https://user-images.githubusercontent.com/62720073/91355417-1e832300-e7bc-11ea-8171-09326d496f24.png">

**Comment by benjamin-cash** [comment]
@bingfu-NOAA I don't have access to the document, but looking at the gridded output in grads you're right the problem doesn't appear there. Thanks everyone for the quick responses - I'll go ahead and close this.

**Comment by junwang-noaa** [comment]
The easy way is to use ncdump to dump out a data field to check if there is
unreasonable value in it.
