### ISSUE TITLE
ice and waves need same pes 

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-s2s-model#172]
**Description**
With the current ESMF version used in UFS-S2S, ice and waves need to run on the same PEs.

**Solution**
The default_vars.sh need to be changed to have ICE and WAV run on same PEs.

**Alternatives**
An update to ESMF has been tested that will allow us to run on the different PEs in the future.

**Additional context**
PR #160

**Comment by junwang-noaa** [comment]
Denise:

*Alternatives*
An update to ESMF has been tested that will allow us to run on the *same*
PEs in the future.

would the updated ESMF allow us to run on different PEs? I thought we don't
need any esmf update if we run cice and ww3 on same PEs.

**Comment by DeniseWorthen** [comment]
I wrote it incorrectly. I've fixed the issue description. Current ESMF we need same PEs. An update (which Rocky had me test) allows us to run on different PEs.

**Comment by rsdunlapiv** [comment]
ESMF_8_1_0_beta_snapshot_27 contains the fix for this.  It should allow running WAVE and CICE on separate PETs.
https://github.com/esmf-org/esmf/tree/ESMF_8_1_0_beta_snapshot_27

**Comment by junwang-noaa** [comment]
Rocky,

Just to confirm that the ESMF_8_1_0_beta_snapshot_27 is ready to use, we
will ask people to install it on hera. orion and wcoss.

**Comment by rsdunlapiv** [comment]
@junwang-noaa yes it should be ready to go
