### ISSUE TITLE
modulefiles format 

### ISSUE THREAD

**Issue by jedwards4b** [ufs-community/ufs-s2s-model#177]
**Description**
It would be nice if cime could load the module files defined in the modulefiles subdirectory of this repository.  A feature was recently added to cime to source files written in sh shell.   However files in this directory appear to be written in csh.

**Solution**
Would it be possible to require these files are written in sh?

**Alternatives**

**Additional context**
Directly reference any issues or PRs in this or other repositories this this is related to and describe how they are related
https://github.com/ESMCI/cime/pull/3689

**Comment by jedwards4b** [comment]
I have opened issue https://github.com/ESMCI/cime/issues/3702 in the cime repo to update this change to allow for csh files.

**Comment by DeniseWorthen** [comment]
We are moving all issues to the new unified repository (ufs-weather+ufs-s2s) and I will move it there if it is still an issue (I suspect it is). Just let me know if you want me to move it. Thanks.

**Comment by jedwards4b** [comment]
No need - this change was in https://github.com/ESMCI/cime/pull/3718 and is already on cime master.
