### ISSUE TITLE
Adding regression tests for fractional grid

### ISSUE THREAD

**Issue by ShanSunNOAA** [ufs-community/ufs-s2s-model#178]
Adding several regression tests to test the fraction grid capability. It involves turning on the switch of "frac_grid=T" and reading in a designated set of oro data, sfc data and gfs data.

**Comment by ShanSunNOAA** [comment]
Thanks. I am merging it to the develop top, and will let you know when it
is done.   -Shan

**Comment by ShanSunNOAA** [comment]
My branch "regression_test_p6_20200924" has merged to the develop top.
Please let me know if there is anything else I need to do for #178.

Thanks,
Shan

**Comment by junwang-noaa** [comment]
Did you run the new test case on hera? @binli2337, can you create a new
baseline and run RT for Shan?

**Comment by ShanSunNOAA** [comment]
Hi Jun,

I did 2 tests on hera:
(1) cpld_fv3_ccpp_384_mom6_cice_cmeps_ww3_1d_bmark_rt
(2) cpld_fv3_ccpp_384_mom6_cice_cmeps_ww3_1d_bmark_rt_frac

(2) is identical to (1), except using fractional landmask and associated
changes.

The output is at /scratch2/BMC/gsd-fv3-dev/Shan.Sun/S2S_RT/rt_87080/. Is
this what you are looking for?

Thanks,
Shan
