### ISSUE TITLE
excessive compile time on dell

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-s2s-model#189]
**Description**
On Sept 8, the compile time for the first executable on dell-p3 was 2276 seconds. 
On Sept 9, it was 11861 seconds, or 3.3 hours. 
On Sept 16, it was again 2092 sec. 
On Sep 19, it was 10295 seconds, or 2.9 hours.

The comparable numbers on hera were 1444 secs (Sept 8) and 1650s (Sept 9).

Older compile logs on dell show consistently ~ 2000 secs (jul 14, aug27).

**Solution**

Determine why the compile time on dell-p3 is so inconsistent. Is it user environment (these examples were committed by various code managers) or a system issue? 
Fix the issue if possible. 

**Alternatives**

**Additional context**

**Comment by SMoorthi-emc** [comment]
It appears that there are some bad nodes on dell.
I have seen some nodes fast and some nodes slow

Moorrhi

**Comment by DeniseWorthen** [comment]
This may be related to running using ecflow on Dell (see also issue #164). I was able to compile the s2s+waves (non-ecflow) on Dell with a compile time of 2304 seconds.

**Comment by DeniseWorthen** [comment]
I am going to close this issue since we have moved to ufs-weather for compiling and running RTs on all platforms. We can re-open if it is found to still be a problem.
