### ISSUE TITLE
[BUG]: cmeps 1d bmark rt test does not use wave template

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-s2s-model#192]
**Describe the bug**

When CMEPS was committed to S2S, the 1d benchmark WW3 RT test (cpld_fv3_ccpp_384_mom6_cice_cmeps_ww3_1d_bmark_rt) did not specify the MOM_input template to be MOM_input_wave_template_025:

 CMEPS: [cpld_fv3_ccpp_384_mom6_cice_cmeps_ww3_1d_bmark_rt](https://github.com/ufs-community/ufs-s2s-model/blob/d7b7081f410eb84902a43c7479e14d44dfed0144/tests/tests/cpld_fv3_ccpp_384_mom6_cice_cmeps_ww3_1d_bmark_rt)
NEMS mediator: [cpld_fv3_ccpp_384_mom6_cice_ww3_1d_bmark_rt](https://github.com/ufs-community/ufs-s2s-model/blob/d7b7081f410eb84902a43c7479e14d44dfed0144/tests/tests/cpld_fv3_ccpp_384_mom6_cice_ww3_1d_bmark_rt)

The 35d CMEPS WW3 test (cpld_fv3_ccpp_384_mom6_cice_ww3_cmeps_35d) did use MOM_input_wave_template_025:

[cpld_fv3_ccpp_384_mom6_cice_ww3_cmeps_35d](https://github.com/ufs-community/ufs-s2s-model/blob/d7b7081f410eb84902a43c7479e14d44dfed0144/tests/tests/cpld_fv3_ccpp_384_mom6_cice_ww3_cmeps_35d)

**Expected behavior**
The ww3 1d bmark rt test should use MOM_input_wave_template_025

**Comment by MinsukJi-NOAA** [comment]
@DeniseWorthen, Will this change the results of `cpld_fv3_ccpp_384_mom6_cice_cmeps_ww3_1d_bmark_rt`?

**Comment by DeniseWorthen** [comment]
Yes, I believe it will.
