### ISSUE TITLE
update FV3 and NEMS 

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-s2s-model#20]
FV3 has been committed with the [0-1] limitation on imported ice fraction. NEMS has also been committed to remove ice-ocean merges in prep_atm. ufs-s2s-model should be updated with new baselines.

**Comment by rsdunlapiv** [comment]
@DeniseWorthen for the [0-1] limitation do you write out any kind of warning if this is more than roundoff?  I could see things going wacky and then this correction masks a bigger problem down the road when we forget about it.  So, if a fraction came in as 1.78 or even 1.1, would you still prefer the model to error out and abort?

**Comment by DeniseWorthen** [comment]
The values we see >1.0 are very small, on the order of 10-15. I did add a write statement in the nems mediator which will flag values >1.0 in the PET log.

**Comment by rsdunlapiv** [comment]
I like it.  This could save someone weeks of time in the future. ;)
