### ISSUE TITLE
Clean up and update regression test script and related files

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [ufs-community/ufs-s2s-model#201]
**Description**
Clean up and update rt.sh and related files

**Solution**
Remove the no-longer-required parts of the script due to the implementation of the one-step cold start. Also update the script and related files to bring in sync with the weather model rt.sh.

**Comment by MinsukJi-NOAA** [comment]
@DeniseWorthen do you run rt.sh on cheyenne at all?

**Comment by DeniseWorthen** [comment]
No, I do not run rt.sh on Cheyenne. I run in a sandbox configuration, where I bring over a canned case of input and run using that canned case.

**Comment by DeniseWorthen** [comment]
Can I close this issue?

**Comment by MinsukJi-NOAA** [comment]
Yes. Thanks.
