### ISSUE TITLE
move parm/ into tests/

### ISSUE THREAD

**Issue by BrianCurtis-NOAA** [ufs-community/ufs-s2s-model#208]
**Description**
The S2S parm/ sits outside of tests/ yet it is strictly for testing

**Solution**
Move parm/ into tests/

**Alternatives**
N/A

**Additional context**
-weather commit doing this: https://github.com/ufs-community/ufs-weather-model/commit/208f36dfa7e13be18967c60cca01a64ca02de4c7

**Comment by DeniseWorthen** [comment]
Can I close this issue?

**Comment by BrianCurtis-NOAA** [comment]
Yes. Looks like i can too?
