### ISSUE TITLE
Port S2S to Stampede

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [ufs-community/ufs-s2s-model#211]
**Description**
Port S2S model to Stampede 2 (TACC)

**Additional context**
Necessary changes will be made to each component repository (MOM6, CICE6, WW3)

**Comment by junwang-noaa** [comment]
@MinsukJi-NOAA since you are working on this, would you please create a wiki on the porting code changes for s2s? E.g., for each component, which files needs to be updated and the related PRs. Thanks.

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA since you are working on this, would you please create a wiki on the porting code changes for s2s? E.g., for each component, which files needs to be updated and the related PRs. Thanks.

@junwang-noaa, a new wiki page is [here](https://github.com/ufs-community/ufs-s2s-model/wiki/Porting-to-a-new-machine)

**Comment by junwang-noaa** [comment]
That's great! Thank you, Minsuk!
