### ISSUE TITLE
List of requirements to restart UFS atmosphere-ocean-ice

### ISSUE THREAD

**Issue by HenryRWinterbottom** [ufs-community/ufs-s2s-model#219]
We are looking for a list of required namelist and parameter file changes required to restart the UFS atmosphere, ocean, and ice model configuration using the latest develop branch revision.

Can someone point us to either a document or a provide us a list of what needs to be changed?

Thank you in advance on behalf of the UFS reanalysis and reforecasting team.

**Comment by junwang-noaa** [comment]
@HenryWinterbottom-NOAA, we will be working on wiki page https://github.com/ufs-community/ufs-s2s-model/wiki/Advanced-Topics#restarting-the-coupled-model, should have something coming out soon.

**Comment by HenryRWinterbottom** [comment]
Thank you @junwang-noaa and @DeniseWorthen 

We appreciate your help!

**Comment by jiandewang** [comment]
@junwang-noaa @HenryWinterbottom-NOAA 
for MOM6 restart:
(1) if there are "MOM.res*.nc" or "MOM6_IC_TS.nc" inside INPUT directory in the current run when it's done, delete them
(2) move "MOM.res*.nc" from MOM6_RESTART directory in the previous run to INPUT directory,
(3) make sure in input.nml, "input_filename" is set as "r"

**Comment by HenryRWinterbottom** [comment]
@junwang-noaa and @jiandewang On RDHPCS Hera, please see the following directories:

/scratch2/BMC/gsienkf/Henry.Winterbottom/work/UFSRNR_DEMO/20180101000000/forecast/cntrl/ (cold-start)
/scratch2/BMC/gsienkf/Henry.Winterbottom/work/UFSRNR_DEMO/20180101060000/forecast/cntrl/ (warm-start)

In the path /scratch2/BMC/gsienkf/Henry.Winterbottom/work/UFSRNR_DEMO/20180101060000/forecast/cntrl/, please see the stdout from the failed run is the run.log file.

We are getting some obscure MPI errors after (or during) the ice model initialization/restart. 

Any thoughts or things that we can try?

**Comment by DeniseWorthen** [comment]
It seems like you are doing a two-step coldstart. Perhaps you have a reason to stick w/ the 2-step, but if you are using the current develop branch, you can use the one-step cold start. 

In nems.configure, you'll need to set start_type to continue. 

I think you also might need to fix your fhrot and start time etc. See the bottom of this page [here](https://github.com/DeniseWorthen/ufs-s2s-model/wiki/Draft:-Restarting-the-Coupled-Model)

**Comment by HenryRWinterbottom** [comment]
@DeniseWorthen Do you have the correct bits describing the one-step  cold start placed somewhere?

**Comment by HenryRWinterbottom** [comment]
@DeniseWorthen @jiandewang @junwang-noaa I am getting the following error when I change the dbug_flag > 0 in nems.configure:

(module_MED:DataInitialize) MED - Initialize-Data-Dependency check Failed for atm
(module_MED:DataInitialize)MED - Initialize-Data-Dependency from ATM NOT YET SATISFIED!!!

**Comment by DeniseWorthen** [comment]
You can see a nems.configure for a startup run (ie, not a restart) here:

/scratch1/NCEPDEV/stmp2/Denise.Worthen/S2S_RT/rt_267474/s2s_control

I don't know if you're re-running in the same directory each time, but you do need to be careful about rpointer.cpl and ice.restart_file. Those get written at the end of each run, so you'll overwrite them if you're running in the same directory. So they'll point your cice and cmeps restarts to the last-written file, not the one you started with.

**Comment by jiandewang** [comment]
@HenryWinterbottom-NOAA @DeniseWorthen 
this is why in my previous comment for MOM the first step is to delete previous IC if you are re-using directory

**Comment by HenryRWinterbottom** [comment]
@DeniseWorthen @jiandewang 

I am not running in the same directory.  This is a new forecast path with the appropriate files linked.

Re: the nems.configure, is there only the changes listed in the table from the comment (above) for a cold versus restart?

**Comment by DeniseWorthen** [comment]
The one-step coldstart is primarily a change in the component codes. FV3 has added export fields and MOM6 can utilize a ocean lag at startup. FV3 always exports these fields, MOM6 triggers off the 'use_coldstart' in the nems.configure. 

So to use the one-step coldstart, you need the warm (concurrent) run sequence, the runtype needs to be startup and the use_coldstart flag needs to be false. Those are all in the nems.configure.

Regarding your MED - Initialize-Data-Dependency from ATM NOT YET SATISFIED message, that is not a function of the dbug_flag setting. The message is written regardless of dbug_flag if CMEPS is finding that the atm import fields are not at the right time stamp. I suspect this is a result of the incorrect model_configure settings for the start hour and fhrot.

Note that the dbug_flag only turns on additional logging messages. It doesn't run the model in debug mode. To do that, you need to compile with DEBUG=Y.

**Comment by DeniseWorthen** [comment]
I've moved the restart wiki page to the ufs-s2s-model page now.

**Comment by junwang-noaa** [comment]
@Denise Worthen - NOAA Affiliate <denise.worthen@noaa.gov> May I  make some
suggestion?  1) change "restart read location" to "input location for
restart runs", 2) add a row of "input files for restart runs" under row "
input location for restart runs", basically move the contents of
https://github.com/ufs-community/ufs-s2s-model/wiki/Model-Restart-Files to
the row  of "input files for restart runs".

**Comment by HenryRWinterbottom** [comment]
@DeniseWorthen I copied the nems.configure that you pointed to above, changed start_type to continue.

I updated the fhrot and start time attributes in model_configure. I still get the same result.

Can you please point me to a path where you have successfully restarted the model?

**Comment by DeniseWorthen** [comment]
@HenryWinterbottom-NOAA  Look in /scratch1/NCEPDEV/stmp2/Denise.Worthen/S2S_RT/restart_rt

This contains the restart tests for S2S using a couple of different resolutions. The C96-1deg restarts are in s2s_control (a 24 hour run), s2s_control_12h (a 12 hour run) and s2s_restart (a restart from the 12h run out to the end of the first day).

@junwang-noaa I'll make the changes as you suggest, no problem.

**Comment by HenryRWinterbottom** [comment]
@DeniseWorthen I tried again, and this time dumping the PET* files. 

It is still failing in path `/scratch2/BMC/gsienkf/Henry.Winterbottom/work/UFSRNR_DEMO/20180101060000/forecast/cntrl`. Can you please take a look and let me know what may be causing the following error message:

`20201011 212457.254 ERROR            PET00 EARTH grid component01:src/addon/NUOPC/src/NUOPC_Driver.F90:433 Internal error: Bad condition  - Initialize data-dependency resolution loop has entered a dead-lock situation.`

`20201011 212457.254 ERROR            PET00 module_NEMS_GRID_COMP.F90:668 Internal error: Bad condition  - Breaking out of subroutine`

`20201011 212457.254 ERROR            PET00 MAIN_NEMS.F90:476 Internal error: Bad condition  - Aborting NEMS`

`20201011 212457.254 INFO             PET00 Finalizing ESMF`

**Comment by DeniseWorthen** [comment]
If this is the restart, where is the initial run?

**Comment by DeniseWorthen** [comment]
In  /scratch2/BMC/gsienkf/Henry.Winterbottom/work/UFSRNR_DEMO/20180101060000/forecast/cntrl/INPUT directory

the files 20180101.060000.fv_core.res.tile5.nc  and fv_core.res.tile5.nc

are identical, so your FV3 restarts appear to be the 6 hour restarts from somewhere. 

Your ice.restart_file points to a 9hr restart file (./RESTART/iced.2018-01-01-32400.nc).
Your rpointer.cpl points to a 9hr restart file (ufs.s2s.cpl.r.2018-01-01-32400.nc)
Your model_configure has your fcst hours to be 9, but fhrot is 3. 

What exact time are you trying to restart from and integrate to?

**Comment by DeniseWorthen** [comment]
Sorry--hit wrong button.

**Comment by HenryRWinterbottom** [comment]
@DeniseWorthen The cold-started run is in /scratch2/BMC/gsienkf/Henry.Winterbottom/work/UFSRNR_DEMO/20180101000000/forecast/cntrl/

We generated a 9-hour forecast for our data-assimilation applications. The analysis will be computed using the 6-hour forecast as a background.

So, based on your comment above I seem to be restarting the ice model from a 9-hour forecast while everything else is from a 6-hour forecast.

**Comment by HenryRWinterbottom** [comment]
@DeniseWorthen I checked to make sure I had all the correct (e.g., 6-hour restart) files for the component model and that the ice.restart_file and rpointer.cpl were updated accordingly.

I am still getting the same error.

Are you able to reproduce my error?

**Comment by DeniseWorthen** [comment]
Normally I would be able to copy your run directory and launch the executable, but I didn't spot the executable in the directory. There was no job script either that I could see, so I don't know how you're running. 

What did you set as fhrot?

**Comment by HenryRWinterbottom** [comment]
@DeniseWorthen I am launching an interactive job to test my setup.

The executable is in `/scratch2/BMC/gsienkf/Henry.Winterbottom/UFS-RNR
1-degree/exec/ufsrnr_forecast.x`

I also tested your executable in the paths you pointed me to previously and got the same result. 

I had tried setting fhrot to 3, 6, and 9 in separate tests and got the same result.

**Comment by DeniseWorthen** [comment]
Please see this directory: /scratch1/NCEPDEV/stmp2/Denise.Worthen/HW2/cntrl

I recursively copied: /scratch2/BMC/gsienkf/Henry.Winterbottom/work/UFSRNR_DEMO/20180101060000/forecast/cntrl
I manually copied the CICE_*nc (the sym links were an issue)
I copied /scratch2/BMC/gsienkf/Henry.Winterbottom/UFS-RNR.1-degree/exec/ufsrnr_forecast.x
I changed fhrot in model_configure to 6
I launched an interactive mode and ran the model
The model ran successfully.

Although this didn't seem to matter, your nems.configure is incorrect. You are using a single write group with 6 write tasks. You have:

MED_petlist_bounds:             6 29
ATM_petlist_bounds:             0 29

It should be 

MED_petlist_bounds:             0 23
ATM_petlist_bounds:             0 29

**Comment by junwang-noaa** [comment]
Thanks, Denise. I think MED_petlist causes the error in Henry's run as it
covers the atm write tasks . Maybe we can put a sample configuration for
the restart test on the wiki page.

**Comment by DeniseWorthen** [comment]
I didn't fix the nems.configure error in my test and it still ran.

**Comment by HenryRWinterbottom** [comment]
@DeniseWorthen Thank you for testing our configuration and pointing me to some things that you found. I am waiting in the queue at the moment for some cores and I will try to reproduce your results. 

The nems.configure, as @DeniseWorthen suggested, didn't make any difference for me either. However, I will update our scripts such that the tasks align as has been recommended. 

@DeniseWorthen For our reference, what does fhrot do/control? Should that always reflect the forecast hour at which you are restarting your experiment? Or is this something else?

**Comment by DeniseWorthen** [comment]
Jun can probably answer more completely, but I think of it as the  "forecast hour restart off-set time", fhrot. It is the off-set in hours from the initial forecast time that the run begins at.

**Comment by SMoorthi-emc** [comment]
FHROT is the restart time.

**Comment by HenryRWinterbottom** [comment]
@DeniseWorthen @junwang-noaa Thank you, that is helpful (I was trying to figure out what the 'ot' might be referring to).

Thanks to @DeniseWorthen I have been able to reproduce her result. I however I have some new questions pertaining to the model.configure setup.

I was able to run with the following two (different) model_configure attributes:

(experiment 1 -- same as @DeniseWorthen )

`total_member:              1
print_esmf:                .true.
PE_MEMBER01:               78
start_year:                2018
start_month:               01
start_day:                 01
start_hour:                00
start_minute:              00
start_second:              00
nhours_fcst:               9.0
RUN_CONTINUE:              .false.
ENS_SPS:                   .false.
dt_atmos:                  900
calendar:                  'julian'
cpl:                       .true.
memuse_verbose:            .false.
atmos_nthreads:            1
use_hyper_thread:          .false.
ncores_per_node:           24
restart_interval:          3
fhrot:                     6`

(experiment 2)

`total_member:              1
print_esmf:                .true.
PE_MEMBER01:               78
start_year:                2018
start_month:               01
start_day:                 01
start_hour:                06
start_minute:              00
start_second:              00
nhours_fcst:               9.0
RUN_CONTINUE:              .false.
ENS_SPS:                   .false.
dt_atmos:                  900
calendar:                  'julian'
cpl:                       .true.
memuse_verbose:            .false.
atmos_nthreads:            1
use_hyper_thread:          .false.
ncores_per_node:           24
restart_interval:          3
fhrot:                     0`

Please note the differences with fhrot and the start_time attributes.

Should I expect a different result with these different configurations? Both run to completion.

**Comment by junwang-noaa** [comment]
Thanks, Denise and Moorthi. Yes, the fhrot is the forecast hour at which
you are restarting your experiment, so in the restart run, the integration
will go from fhrot to nhours_fcst.
I see, the code is able to run when med is on some write tasks, but now it
has to wait for the write tasks to finish, so aligning the med to the atm
forecast tasks would allow the test to run faster.

**Comment by DeniseWorthen** [comment]
From the perspective of atm users, this may make sense. But no other component would use this sort of system. You're keeping the initial time the same (sday,shour) and saying that you're restarting it 6 hours after that initial time. The ocean and ice would normally just say that if I'm restarting the model at 6hours, then that is my starting time also.

**Comment by HenryRWinterbottom** [comment]
@DeniseWorthen It is a function of having (at least 3 at the moment) DA systems feeding into the UFS. There may be a better way to do this, we just haven't yet discovered or engineered a means.

However, if it does not change the result, it may not matter.

Thoughts?

**Comment by junwang-noaa** [comment]
Henry, the setting 1 is what we call restart, and setting 2 is what we
call warm start. Both could use the same restart files. But 1) is a
continuous run from a previous control, so the output files will be
fh06-fh09, with the initial run time the same as control.  while 2) is a
new test run, so the output files should be fh00-fh03 with a new initial
run time.

**Comment by HenryRWinterbottom** [comment]
@junwang-noaa Thank you for the clarification. I believe warm-start is what we want since we will be creating a new analysis from which the atmosphere and ocean/ice components will be restarting.

As long as the results (assuming no DA) are identical, then this should work.

Does this help to clarify what we are attempting to accomplish?

**Comment by junwang-noaa** [comment]
For GFS.v15 cycled runs with DA, we are using 2). For GFS.v16 cycled runs
with DA and IAU, we are using 1) but with adjusted output time stamps to
mark the cycle time.

**Comment by junwang-noaa** [comment]
Are you using IAU in atmosphere?

**Comment by HenryRWinterbottom** [comment]
@junwang-noaa At the moment no, in the future yes.

**Comment by junwang-noaa** [comment]
I see, so 2) is OK. For IAU, we have to use 1).

**Comment by HenryRWinterbottom** [comment]
@junwang-noaa For the IAU, what is the issue you encounter if you try to use option (2)?

**Comment by junwang-noaa** [comment]
For IAU for cycle 0, we need to start integration from fh=-3, while warm
start from that time could cause lots of issues in the model output fields
with bucket=6hr.

**Comment by HenryRWinterbottom** [comment]
@junwang-noaa Thank you for the information. As we move toward IAU with our configuration/experiments, we will remain cognizant of this issue. Further, if we figure out a way around this, we will also feed that information back to your group.

**Comment by HenryRWinterbottom** [comment]
@DeniseWorthen @jiandewang @junwang-noaa @SMoorthi-emc Thank you for all of your help with this issue. I am closing this ticket.
