### ISSUE TITLE
Decide CCPP configuration for coupled benchmark 4

### ISSUE THREAD

**Issue by arunchawla-NOAA** [ufs-community/ufs-s2s-model#30]

**Comment by JessicaMeixner-NOAA** [comment]
As a first test, we'd like to run with the options of prototype 3.1, which corresponds to using  [parm/input.benchmark.nml.IN](https://github.com/ufs-community/ufs-s2s-model/blob/develop/parm/input.benchmark.nml.IN) 

In addition, for prototype 4, we will want the same as above with the additional 
&gfs_physics_nml options: 
  cplwav       = .true.
  cplwav2atm   = .true. 
which rely on having an updated fv3atm [PR](https://github.com/NOAA-EMC/fv3atm/pull/44)  which has a corresponding ccpp-physics [PR](https://github.com/NCAR/ccpp-physics/pull/378) as well.

I'm not sure if that corresponds to two suite definition files or not.

**Comment by junwang-noaa** [comment]
A new CCPP suite file FV3_GFS_v15p2_coupled.xml for current benchmark 3.1 is added in FV3 PR #86. It is used in s2s 1 day benchmark3.1 test and in the 4 components fv3-mom6-cice5-ww3 benchmark test. The physics option is same as GFS v15p2 except that nsst is turned off and sfc_ocean and sfc_cice  are turned on for coupled run.

**Comment by junwang-noaa** [comment]
When the s2s PR #64 is committed, the issue can be closed.
