### ISSUE TITLE
create regression test for two-way wave-atm coupling for a FV3-MOM6-CICE5-WW3 test

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-s2s-model#31]
This test will have wave-atm two-way coupling added to a new compset for FV3-MOM6-CICE5-WW3. 

When wave-ocean coupling is added, it will be added to this test and this test will not be retained.

**Comment by JessicaMeixner-NOAA** [comment]
The update in fv3atm [PR](https://github.com/NOAA-EMC/fv3atm/pull/44) for wave to atm feedback, also has a bug fix which changes answers.  Has a new baseline already been created for ufs-s2s-model that corresponds to this commit or should I go ahead and make that while making the new test?

**Comment by junwang-noaa** [comment]
Bin is working on this commit on s2s side. He tested s2s with Moorthi's
branch and did some longer run tests, if that runs well, he will create a
new baseline. So far, please create a n s2s fv3-wav test case.

**Comment by JessicaMeixner-NOAA** [comment]
Sounds good.  If @binli2337 points me to the long runs I'll make sure the runs get analyzed.  Test for the s2s with WW3-ATM coupling is in progress....

**Comment by lgannoaa** [comment]
@JessicaMeixner-NOAA and @binli2337 ,

After research on the issue that some fix files were pointed from personal location. I found the GFS using same solution in linking/copy fix files. GFS team used the fix file from glopara group account local location on supporting machine. Therefore, files point to Bin.Li should be changed to a group account. Please see the modified link_fv3gfs.sh below:

pwd:
/scratch1/NCEPDEV/global/Lin.Gan/git/coupled-workflow-crow
Found file pointed to Bin.Li personal location:
./fix/fix_mom6 -> /scratch2/NCEPDEV/climate/Bin.Li/S2S/fix/fix_prep_benchmark3/fix_mom6
./fix/fix_cice5 -> /scratch2/NCEPDEV/climate/Bin.Li/S2S/fix/fix_prep_benchmark3/fix_cice5
./fix/fix_ocnice -> /scratch2/NCEPDEV/climate/Bin.Li/S2S/fix/fix_prep_benchmark3/fix_ocnice
./fix/fix_fv3grid -> /scratch2/NCEPDEV/climate/Bin.Li/S2S/fix/fix_prep_benchmark3/fix_fv3grid

Research:
In link_fv3gfs.sh, GFS using "glopara" local location to copy/link the fix files:
---
FIX_DIR="/scratch1/NCEPDEV/global/glopara/fix"
$LINK $FIX_DIR/* .
---
Will use the same solution.

File purposed to change: 
**/scratch1/NCEPDEV/global/Lin.Gan/git/coupled-workflow-crow/sorc/link_fv3gfs.sh**

Please let me know if you have any questions.

**Comment by JessicaMeixner-NOAA** [comment]
@lgannoaa  I agree we should not be pointing to anything in a personal directory.  Do we want to use the glopara account or I'm slowly working on getting access to climate group account for myself and a few others.   

If you want to put it in the globpara, that's fine I just need to figure out what is different (if anything) from the /scratch1/NCEPDEV/global/glopara/fix and ours and what is added, and make sure the added files have been cleaned up so we aren't keep a lot of files we don't need.

**Comment by lgannoaa** [comment]
@JessicaMeixner-NOAA I recommend to put those fix files under climate group account. The GFS team already justified their solution of linking/copy fix files from glopara. This solution will be in-line with EE2 review requirements.

**Comment by lgannoaa** [comment]
@JessicaMeixner-NOAA @binli2337 
I discovered the ice*.nc files are not bit identical. Please contact developer to change these NC file to not be time stamped. It can be made bit identical. Please create an issue for this item. Thanks

**Comment by JessicaMeixner-NOAA** [comment]
@lgannoaa can you use a different comparison method for that file then? The contents minus the datestamp should be identical.  This is a CICE5 output and we have plans to move to CICE6 soon so this is a low - to - no priority item for us to address for CICE5.

**Comment by JessicaMeixner-NOAA** [comment]
Also @lgannoaa  I just noticed this is all for workflow, and this issue is for a ufs-s2s-model regression test.  Can we move the workflow conversations to an issue for the workflow?

**Comment by lgannoaa** [comment]
Ok thanks @JessicaMeixner-NOAA 
I understand CICE5 is not main concern at this time. As regard to where this discussion should be, I do not know. Please fell free to remove the conversion as need. The EE2 does require bid identical results.
