### ISSUE TITLE
Adding CCPP to coupled system

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-s2s-model#42]
This issue is for the ufs-s2s-model pull request: 

https://github.com/ufs-community/ufs-s2s-model/pull/7

Add CCPP capability in coupled model

**Comment by junwang-noaa** [comment]
CCPP will provide 3 CCPP suite files (2 for the two new IPD tests Bin added, one for benchmark 3.1)
s2s will have 2 new tests added besides current 8 RT tests.  
Corresponding CCPP test will be created. 
Both IPD tests and CCPP tests will be run on REPRO mode, and the results should be identical. An 8 cases 35 day long runs using CCPP PROD will be conducted separately.
IPD tests and REPRO CCPP tests will be droped at the end of transition.

Associated issues:
1. [create regression test for two-way wave-atm coupling for a FV3-MOM6-CICE5-WW3 test](https://github.com/ufs-community/ufs-s2s-model/issues/31)
2. [Make 1 day reg test that matches a benchmark case](https://github.com/ufs-community/ufs-s2s-model/issues/46)
3. [Set of tests for IPD v CCPP for longer runs that mimic benchmarks](https://github.com/ufs-community/ufs-s2s-model/issues/47)
4. [Decide CCPP configuration for coupled benchmark 4](https://github.com/ufs-community/ufs-s2s-model/issues/30)
5. [IPD and CCPP test comparison and drop IPD test in S2S RT](https://github.com/ufs-community/ufs-s2s-model/issues/62)

**Comment by DeniseWorthen** [comment]
@junwang-noaa Can we close this issue on ufs-s2s-model?

**Comment by junwang-noaa** [comment]
CCPP was added to coupled system, close ticket.
