### ISSUE TITLE
Finalize end-to-end workflow for coupled modeling

### ISSUE THREAD

**Issue by jkuang-exploro** [ufs-community/ufs-s2s-model#45]
Need to bring in external scripts that are being run by @binli2337 into the global-workflow.

**Comment by arunchawla-NOAA** [comment]
@binli2337 work with @JianKuang-NOAA to make sure that all the scripts that are needed for benchmark are part of the global workflow in one way or the other. If the remaining scripts need to find a home then perhaps we can put them in ufs-utils repo. 

@AvichalMehra-NOAA we will need someone from the coupled modeling team to certify that everything is working ok once they are done.

**Comment by JessicaMeixner-NOAA** [comment]
At this point is this issue considered "done"?  I know we have an issue with the wave post, but that can be a separate issue in the global-workflow repo?

**Comment by jkuang-exploro** [comment]
My opinion is, since this task is focus on the workflow as a whole, it should be marked "done". Another issue should be created for any localized issue.
