### ISSUE TITLE
Bringing in wave features

### ISSUE THREAD

**Issue by arunchawla-NOAA** [ufs-community/ufs-s2s-model#49]
Wave capabilities in the feature/gfsv16b branch need to be brought back to coupled branch for prototype 4 and connecting to CROW. 

Need help from coupled modeling team to identify the features and configuration fixed files that need to be placed in fixed directory

**Comment by junwang-noaa** [comment]
Arun,

It looks to me this issue is related to global workflow. So on model side,
we just need to provide information on: how to compile the code with WW3,
how to run the model with WW3 (changes in model configuration, namelist,
fixed files etc), do we need to consider different resolutions?

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa I agree this is related to the global workflow. 

On the model side: For compiling WW3, there will be a new "appBuilder" file which we will need to point to in the compile workflow script. We do not have the same compile.sh script that is being used in the ufs-weather-model for s2s at this time. 

For WW3, we are currently just targeting one resolution for benchmark 4.  There will be additional grids/resolutions possibly in the future.  I will identify any fix files and configuration that will be needed.  I am taking the prep, init, and post scripts that @ajhenrique developed for GFSv16 and will make any modifications that are needed to run for the s2s case.

**Comment by arunchawla-NOAA** [comment]
@JessicaMeixner-NOAA is this completed?

**Comment by jkuang-exploro** [comment]
This is done a long time ago.

**Comment by lgannoaa** [comment]
The test was done a while ago by me. I turn over the code back to Jian who is the code manager for CROW. 
Thank you Jian for confirm this is done. I will close this ticket.
