### ISSUE TITLE
Revisit Cold Starts

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-s2s-model#53]
So that we can run all components simultaneously, we first run a 'cold start' run sequence ([see here](https://github.com/ufs-community/ufs-s2s-model/blob/develop/parm/nems.configure.medcold_atm_ocn_ice.IN)) to generate mediator restart files and then use the normal run sequence ([see here](https://github.com/ufs-community/ufs-s2s-model/blob/develop/parm/nems.configure.med_atm_ocn_ice.IN))

There is a question that if we actually initialize the data fields from MOM6/CICE and possibly rewind after the first step of MOM6 or utilize different run sequences, can we get rid of the "cold start"?  (There is an ESMF feature that you can have multiple run sequences, this would require possible cap updates as well).

**Comment by mvertens** [comment]
Can we please also look at the way that CESM is doing this with MOM6. It
totally removes the need for a cold start and has been approved by the MOM6
folks. It does not require multiple run sequences. I am happy to arrange a
call if that would be helpful.

**Comment by JessicaMeixner-NOAA** [comment]
@mvertens Yes, we would appreciate seeing how CESM is doing this with MOM6. Let's schedule a call when this is higher on the priority list?
