### ISSUE TITLE
convert NEMSCompsetRun to rt.sh in s2s

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-s2s-model#85]
In this issue, simple regression test script test system (rt.sh) will be  set up to run s2s regression test, which is currently supported by NEMSCompsetRun.

**Comment by MinsukJi-NOAA** [comment]
12 CCPP PROD tests were converted to rt.sh: #75 and #78. All RT's passed against NEMSCompsetRun-generated baselines. New baselines were generated on Orion using rt.sh.

**Comment by MinsukJi-NOAA** [comment]
2 CCPP PROD debug tests were converted to rt.sh: https://github.com/ufs-community/ufs-s2s-model/pull/88. All RT's passed on Hera and Orion.
