### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by rgrumbine** [ufs-community/ufs-s2s-model#87]
demo of what happens when somebody not on the privileged list hits "submit new issue".
Note that it includes:
- nobody assigned to it
- no labels (e.g. bugs)
- no connection to projects
- no connection to milestones
- no linked pull requests

also note that contrary to, e.g., https://www.joelonsoftware.com/2000/08/09/the-joel-test-12-steps-to-better-code/
none of the issues are labeled 'bug', so there is no bug tracking.

**Comment by junwang-noaa** [comment]
According to github:  Any GitHub user can create an issue in a public
repository where issues have not been disabled
<https://help.github.com/en/articles/disabling-issues>.   So if you signed
in your github account, please create an issue at following repository to
see there is any problem:

https://github.com/ufs-community/ufs-s2s-model
https://github.com/NOAA-EMC/fv3atm/

**Comment by rgrumbine** [comment]
What you're commenting on is what happens when I execute 'new issue' on ufs-s2s-model.

There are no assignees, no labels, etc.. I cannot do any of those functions.
