### ISSUE TITLE
rt.sh has error on compile when using cmeps

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-s2s-model#97]
In testing the cmeps-capable s2s-model, it was found that compiling inside rt.sh (ie, using compile line in rt.conf)  causes the build to fail. The issue appears to be the clean function in the component_CMEPS.mk

**Comment by MinsukJi-NOAA** [comment]
This issue needs to be addressed in NEMS: GNUmakefile and component makefiles, as you pointed out.

**Comment by MinsukJi-NOAA** [comment]
When 'make app=<> clean' is called on CMEPS component, it somehow checks for the existence of modules.nems in NEMS/src/conf, which is copied from ufs-s2s-model/modulefiles/${MACHINE}/fv3_coupled during the build (not clean). If modules.nems is manually copied into NEMS/src/conf, then make clean is called, the error does not occur.

**Comment by DeniseWorthen** [comment]
I've created an issue on the NEMS page also referencing this issue for details.

**Comment by MinsukJi-NOAA** [comment]
Closing this issue as the fix has been merged.
