### ISSUE TITLE
confirm performance (speed) of ccpp vs ipd on hera

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-s2s-model#98]
There have been some hints that ccpp may perform slower than ipd in ufs-s2s. For example, @JessicaMeixner-NOAA reports that additional PEs needed to be added to the ATM to get a run time under P2 6 hour wall clock. 

@DeniseWorthen reports that on Cheyenne (using CMEPS or NEMS) 8 hours of wall clock completed only ~15 days of integration. This may have been an issue with Cheyenne hardware at the time; a second test will be conducted to confirm. 

@SMoorthi-emc reports seeing no speed issue for CCPP vs IPD and is able to get about speeds of about 10mins/day on Hera using 2 threads for ATM.

**Comment by climbfuji** [comment]
Thanks for reporting this. If this is indeed the case for the s2s, I need to take a closer look. Can you check please that you are using the same compiler flags (i.e. not REPRO=Y) for both IPD and CCPP?

**Comment by DeniseWorthen** [comment]
I've building using a new ccpp-cmeps app builder file like so:

COMPONENTS=( FMS CCPP FV3 MOM6 CICE CMEPS )

FV3_MAKEOPT="CCPP=Y SUITES=FV3_GFS_2017_coupled,FV3_GFS_2017_satmedmf_coupled,FV3_GFS_v15p2_coupled CMEPS=Y"

And the original (IPD) version like so:

COMPONENTS=( FMS FV3%CMEPS=Y MOM6 CICE CMEPS )

The %CMEPS=Y only triggers the module_EARTH_GRID_COMP.F90 to expect the CMEP mediator. There are no CMEPS specific ifdefs in FV3.

Are there other build options for FV3 that I would need to confirm are the same?

**Comment by climbfuji** [comment]
> I've building using a new ccpp-cmeps app builder file like so:
> 
> COMPONENTS=( FMS CCPP FV3 MOM6 CICE CMEPS )
> 
> FV3_MAKEOPT="CCPP=Y SUITES=FV3_GFS_2017_coupled,FV3_GFS_2017_satmedmf_coupled,FV3_GFS_v15p2_coupled CMEPS=Y"
> 
> And the original (IPD) version like so:
> 
> COMPONENTS=( FMS FV3%CMEPS=Y MOM6 CICE CMEPS )
> 
> The %CMEPS=Y only triggers the module_EARTH_GRID_COMP.F90 to expect the CMEP mediator. There are no CMEPS specific ifdefs in FV3.
> 
> Are there other build options for FV3 that I would need to confirm are the same?

This looks fine to me.

**Comment by DeniseWorthen** [comment]
I'm going to close this issue as being OBE. We have fully integrated CCPP now and if we see performance issues we will deal w/ them as a new issue.
